baseURL = ''
languageCode = 'en-us'
title = 'Atomsite'
theme = "JoeTheme"
timeout = "21600s"


[menu]
  [[menu.main]]
    name = "About"
    pre = "about"
    url = "/about/" 
    weight = 1
  [[menu.main]]
    name = "Research"
    pre = "research"
    url = "/research/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    pre = "publications"
    url = "/publications/"
    weight = 3
  #[[menu.main]]
  #  name = "Posts"
  #  pre = "posts"
  #  url = "/posts/"
  #  weight = 3
  [[menu.main]]
    name = "Photography"
    pre = "photos"
    url = "/photos/"
    weight = 4
  #[[menu.main]]
  #  name = "Tags"
  #  pre = "tag"
  #  url = "/tags/"
  #  weight = 5

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 2
    ordered = false
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false

